# Generated by Django 5.1.7 on 2025-04-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentrover', '0003_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='agency',
        ),
    ]
